
0b
 ****  Installateur de NuTyX #ARCH# #VERSION_NUTYX#  ****** ##VERSION_KERNEL# ****
07
Tapez 0center07 pour une initialisation normale!
07
Tapez 0c80007, 0c102407 ou 0c128007
En cas d'echec de l'initialisation normale.

Si vous avez des problemes de reconnaissance de materiel, tapez0c noacpi07

Tapez0c sda1..sda1007, 0csdb1..sdb10 07, 0csdc1..sdc1007 ou 0csdd1..sdd1007
en fonction de la partition sur laquelle se trouve NuTyX que
vous souhaitez lancer depuis ce CD-ROM. 

