#!/bin/sh
########################################################################
# Begin network
#
# Description : Network Control Script
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
#               Nathan Coulson - nathan@linuxfromscratch.org
#               Kevin P. Fleming - kpfleming@linuxfromscratch.org
#               DJ Lucas - dj@linuxfromscratch.org
# Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            $network
# Required-Start:      $local_fs swap localnet
# Should-Start:        $syslog
# Required-Stop:       $local_fs swap localnet
# Should-Stop:         $syslog
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts and configures network interfaces.
# Description:         Starts and configures network interfaces.
# X-LFS-Provided-By:   LFS
### END INIT INFO
. /lib/lsb/init-functions

if [ ! -f /etc/sysconfig/network ]; then
  cat > /etc/sysconfig/network << "EOF"
HOSTNAME='nutyx'
MANAGER='cli'
EOF
fi

# Network configuration
. /etc/sysconfig/network

NM_PIDFILE="/var/run/NetworkManager.pid"
WICD_PIDFILE="/var/run/wicd/wicd.pid"

if [ "${MANAGER}" == "" ]; then
	MANAGER="cli"
	if [ -f /usr/sbin/NetworkManager ]; then
		MANAGER="networkmanager"
	fi
	if [ -f /usr/bin/wicd ]; then
		MANAGER="wicd"
	fi
fi
case "${1}" in
  start)
	case "${MANAGER}" in
		networkmanager)
			if [ -f /usr/sbin/NetworkManager ]; then
				if [ ! -d /var/run/NetworkManager ]; then
					install -d -o root -g root -m 755 /var/run/NetworkManager
				fi
				log_info_msg "Starting NetworkManager daemon..."
				start_daemon /usr/sbin/NetworkManager
				if [ "${NETWORKWAIT}" == "yes" ]; then
					[ -z "${LINKDELAY}" ] && LINKDELAY=10
					log_info_msg "Waiting for network..."
					nm-online -q --timeout=$LINKDELAY || nm-online -q -x --timeout=30
					[ "$?" = "0" ] && log_success_msg "Network startup" || log_failure_msg "Network startup"
					[ -n "${NETWORKDELAY}" ] && /bin/sleep ${NETWORKDELAY}
				fi
			else
                                echo "the package networkmanager seems not to be install"
                                echo "check the file /etc/sysconfig/network"
			fi;;
		wicd)
			if [ -f /usr/bin/wicd ]; then
				if [ -e $WICD_PIDFILE ]; then
					echo "Wicd appears to already be running"	
					echo "If this is not the case, then remove"
					echo "$WICD_PIDFILE, check the file /etc/sysconfig/network"
					echo "and try again"
				else
					log_info_msg "Starting the wicd Daemon..."
					start_daemon /usr/bin/wicd 1>/dev/null
					evaluate_retval
					if grep -v ^# /etc/fstab | grep _netdev > /dev/null; then
						while ! grep "nameserver" /etc/resolv.conf ;
							do
								if [ $NETWORKDELAY -gt 0 ]; then
									sleep 1
									echo -n .
									let NETWORKDELAY=$NETWORKDELAY-1
									if [ $NETWORKDELAY -lt 1 ]; then
										log_info_msg "Time out"
										echo_failure
									exit 1
								fi
							fi
						done
						log_info_msg "Network successfully configured..."
						echo_ok
					fi
				fi
			else
                                echo "the package wicd seems not to be install"
                                echo "check the file /etc/sysconfig/network"

			fi;;
		cli)
			# Start all network interfaces
			for file in /etc/sysconfig/ifconfig.*
			do
				interface=${file##*/ifconfig.}
				# Skip if $file is * (because nothing was found)
				if [ "${interface}" = "*" ]; then
					continue
				fi
				if [ -f /etc/wpa_supplicant.conf.${interface} ] && [ -x /sbin/wpa_supplicant ]; then
					wpa_supplicant -B -c/etc/wpa_supplicant.conf.${interface} -i${interface} \
					-P /var/run/wpa_supplicant.${interface}
					sleep 2
				fi
				/sbin/ifup ${interface}
			done
		;;
	esac;;
  stop)
	case ${MANAGER} in
		networkmanager)
			if [ -f /usr/sbin/NetworkManager ]; then
				log_info_msg "Stopping NetworkManager daemon..."
				killproc /usr/sbin/NetworkManager
			else
				echo "the package networkmanager seems not to be install"
				echo "check the file /etc/sysconfig/network"
			fi;;
		wicd)
			if [ -e $WICD_PIDFILE ]; then
				log_info_msg "Stopping the wicd Daemon..."
				wicd-cli -xyz 1>/dev/null
				kill $(cat $WICD_PIDFILE)
				evaluate_retval
			else
				echo "wicd appears not to be running..."
				echo "check the file /etc/sysconfig/network"
			fi;;
		cli)
			# Reverse list
			net_files=""
			for file in  /etc/sysconfig/ifconfig.*
			do
				net_files="${file} ${net_files}"
			done

			# Stop all network interfaces
			for file in ${net_files}
			do
				interface=${file##*/ifconfig.}

				# Skip if $file is * (because nothing was found)
				if [ "${interface}" = "*" ]
				then
					continue
				fi
				/sbin/ifdown ${interface}
				if [ -f /var/run/wpa_supplicant.${interface} ]; then
					kill `cat /var/run/wpa_supplicant.${interface}`
				fi
			done
      			;;

	esac
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   *)
      echo "Usage: ${0} {start|stop|restart}"
      exit 1
      ;;
esac

exit 0

# End network
