#!/bin/bash

# get read of the doc categories packages
for i in `cards list -i|cut -d " " -f1|grep doc$`
do 
  cards remove $i
done

# get read of the devel categories packages
for i in `cards list -i|cut -d " " -f1|grep devel$`
do
  cards remove $i
done

# get read of the man categories packages
for i in `cards list -i|cut -d " " -f1|grep man$`
do
  cards remove $i
done

# get read of the only devel packages
for i in man-db man-db patch bison m4 libtool texinfo \
pkg-config automake autoconf make nasm groff perl less \
gawk 
do
  cards remove -a $i
done

mkinitramfs

mv /root/makelfs /
mv /root/logs /

cd /

for dir in opt bin etc lib root run sbin usr var
do 
  mksquashfs $dir ISO/isolinux/boot/$dir.squashfs
done

tar cJvf nutyx_`date +%Y%m%d`-1-`uname -m`.cards.tar.xz boot
