#!/bin/bash
if [ -z "$LOG" ]; then
   PASS=`pwd`
   PASS=`basename $PASS`
   LOG=$HOME/logs/$PASS
fi
if [ ! -d $LOG ]; then
	mkdir -p $LOG
fi

error() {
echo " Error produced in $i"
exit 1
}
if [ ! -f list ];then 
	LIST="$HOME/bin/list"
else
	LIST="list"
fi
for i in `cat $LIST`
do
   BUILD="yes"
   PKGMK="pkgmk.passes"
   if [ -f ${LOG}/$i.log ]; then
      if ( grep "^=======>" ${LOG}/$i.log|grep "succeeded"  > /dev/null);then
         BUILD="no"
      else
         BUILD="yes"
      fi

   fi
   if [ "$BUILD" == "yes" ]; then
      if [ "$PASS" == "chroot" ]; then
           cd ${i}
      else
         cd ${i}@*
      fi
      NAME=`echo $i|cut -d "@" -f1`
      if [ "$NAME" != "kernel" ];then
      	$PKGMK -cf ../../bin/pkgmk.conf.passes -i -kw 2>&1|tee ${LOG}/$i.log || exit 1
      else
        $PKGMK -d -cf ../../bin/pkgmk.conf.passes -i -kw
      fi
      if ( grep "^=======>" ${LOG}/$i.log| tail -1 |grep "ERROR"  > /dev/null);then
         exit 1
      fi
      cd ..
   fi
done

