#!/bin/bash
#
#  cards
#
#  Copyright (c) 2007-2013 by NuTyX team (http://nutyx.org)

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
#  USA.
#

source /etc/pkgmk.conf

if [ $# -lt 1 ]; then
        echo 1>&2
        echo 1>&2 'Usage: pkgmkall <Package> (pkgmkall kde par exemple)'
        echo 1>&2
        exit 1
fi
erreur_deps(){
echo "Erreur de dépendances"
rm -r $TMP
exit 1
}
erreur() {
echo "Erreur de compilation"
rm -r $TMP
exit 1
}
DRY=false
if [ "$1" == "--dry" ];then
        DRY=true
	shift
fi
if [ "`pkginfo -b $1`" != "0" ]; then 
	echo "`basename $0` $VERSION: package $1 is installed"
	exit 1
fi
TMP=`mktemp -d`
cards depends $1| cut -d " " -f1 > $TMP/list
if grep "WARNING" $TMP/list ; then
        erreur_deps
fi
if [ $DRY == true ]; then
# On supprime la dernière ligne cad
# le paquet passé en argument que
# l'on veut contruire
	LINE=`wc -l $TMP/list|cut -d " " -f1`
	sed -i "${LINE}d" $TMP/list
fi

for i in `cat $TMP/list`
do
        cd $i
        pkgmk -d -i || erreur
done
rm -r $TMP

# End of file
