#!/bin/sh
# **************************************************************************
#              BEGIN of SCRIPT
# **************************************************************************

if [ $# -lt 1 ]; then
	echo "need to know the category to generate"
	exit 1
fi

GROUP=${1}

cd /srv/nutyx/saravane/latest/${GROUP}/
rm -f {index.html,MD5SUM}

TMP=`mktemp -d`

cat > $TMP/index.html << "EOF"
 <!DOCTYPE html>
 <html>
 <head>
  <meta charset="utf-8" />
  <link rel="shortcut icon" href="../favicon.ico">
  <link rel="stylesheet" href="../css/nutyx.css" />
   <style type="text/css">
    body
    {
      font-family: Verdana, sans-serif;
      font-size: 85%;
      padding: 2em;
    }
    table
    {
      border: solid #e5dccf 1px;
      font-size: 85%;
    }
    td
    {
      padding: 6px;
    }
    tr.header
    {
       background-color: #e5dccf;
    }
    tr.odd
    {
      background-color: #f7f3ed;
    }
    tr.even
    {
       background-color: #fcf9f8;
    }
   </style>
EOF
DATE=`date +%Y%m%d\ %H%M`
echo "<title>NuTyX saravane $DATE</title>" >> $TMP/index.html
cat >> $TMP/index.html << "EOF"
 </head>
 <body>
  <header>
  <img src="../graphics/logo_nutyx_120.png" alt="logo nutyx" />
 </header>
    <nav>
        <ul>
            <li><a href="http://nutyx.org">Home</a></li>
            <li><a href="http://git.tuxfamily.org/?p=nutyx/saravane.git">GIT</a></li>
            <li><a href="http://downloads.nutyx.org/saravane/latest/system/">system</a></li>
            <li><a href="http://downloads.nutyx.org/saravane/latest/server/">server</a></li>
            <li><a href="http://downloads.nutyx.org/saravane/latest/desktop/">desktop</a></li>
        </ul>
    </nav>
 
EOF
if [ -f lastcommit ]; then
  cat  >> $TMP/index.html << "EOF"
  <h3>Last Commit on git</h3>
  <table width="100%" cellspacing="0">
   <tr class="header"><td>Author</td><td>Email</td><td>Description</td><td>Date</d></tr>
EOF
  cat lastcommit >> $TMP/index.html
  rm lastcommit
  echo "</table>" >> $TMP/index.html
fi
echo "
    <h3>Packages NuTyX - Saravane - $DATE -  $GROUP</h3>" >> $TMP/index.html
cat >> $TMP/index.html << "EOF"
    <table width="100%" cellspacing="0">
      <tr class="header"><td>Name</td><td>Version</td><td>Description</td></tr>
EOF
CLASS="even"
for file in *
do
        if [ "$CLASS" == "even" ]; then
                CLASS="odd"
        else
                CLASS="even"
        fi
        name="$file"
        if [ ! -f $file/$name.info ]; then
                echo "$file is obsolete, removed folder $file..."
                rm -rf $file
                continue
        else
                version="`head -1 $file/Pkgfile|cut -d "=" -f2`"
                description="`head -1 $file/$name.info`"
                if [ ! -f $file/MD5SUM ]; then
                        echo "$file/MD5SUM not found, skip..."
                        continue
                fi
                echo "<tr class=\"$CLASS\"><td width="20%"><a href=\"${file}/\">${name}</a></td><td width="10%">$version</td><td width="70%">$description</td></tr>" >> $TMP/index.html
                echo "`md5sum $file/MD5SUM|cut -d " " -f1`:$file" >> $TMP/MD5SUM
        fi
done
cat >> $TMP/index.html << "EOF"
   </table>
       <footer>
        <p id="foot">... <img src="../graphics/logo_nutyx_25.png" alt="nutyx petit logo"> ...<br />
        &copy; 2007 - 2014 <a href="http://nutyx.org">NuTyX</a> | Design by <a href="http://ptite.cahouet.net">La ptite Cahouet</a>.</p>
    </footer>
 </body>
</html>
EOF
mv $TMP/index.html .
mv $TMP/MD5SUM .
rm -r $TMP
# ********************************************************************
#                     END of SCRIPT
# ********************************************************************
